//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    
    public partial class func_GetReorderProduct
    {
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string ProductCategory_Name { get; set; }
        public int Product_ReOrederLevel { get; set; }
        public string Unit_Name { get; set; }
        public double CurrentInventory_CurrentQuantity { get; set; }
    }
}
