//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    
    public partial class Func_TotalStock
    {
        public int Product_SlNo { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string ProductCategory_Name { get; set; }
        public string Unit_name { get; set; }
        public bool Product_IsFinishedGoods { get; set; }
        public bool Product_IsRawMaterial { get; set; }
        public double PurchaseInventory_TotalQuantity { get; set; }
        public double PurchaseInventory_ReceiveQuantity { get; set; }
        public double PurchaseInventory_ReturnQuantity { get; set; }
        public double PurchaseInventory_DamageQuantity { get; set; }
        public double SaleInventory_TotalQuantity { get; set; }
        public double SaleInventory_ReceiveQuantity { get; set; }
        public double SaleInventory_ReturnQuantity { get; set; }
        public double SaleInventory_DamageQuantity { get; set; }
        public double CurrentInventory { get; set; }
    }
}
