//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    
    public partial class Get_DamagedProduct
    {
        public string ProductCategory_Name { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public Nullable<double> DamageDetails_DamageQuantity { get; set; }
        public string Unit_Name { get; set; }
    }
}
