//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    
    public partial class Get_SaleInvoiceByQuotation
    {
        public int QuotationDetails_SlNo { get; set; }
        public decimal QuotationDetails_Rate { get; set; }
        public decimal QuotationDetails_Discount { get; set; }
        public decimal QuotationDetails_Tax { get; set; }
        public decimal QuotationDetails_Freight { get; set; }
        public decimal QuotationDetails_TotalAmount { get; set; }
        public int Product_SlNo { get; set; }
        public string ProductCategory_Name { get; set; }
        public string ProductCategory_Description { get; set; }
        public string Unit_Name { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public bool Product_IsRawMaterial { get; set; }
        public bool Product_IsFinishedGoods { get; set; }
        public int Product_ReOrederLevel { get; set; }
        public decimal Product_Purchase_Rate { get; set; }
        public decimal Product_SellingPrice { get; set; }
        public string AddBy { get; set; }
        public int QuotationMaster_SlNo { get; set; }
        public string QuotationMaster_InvoiceNo { get; set; }
        public string QuotationMaster_CallanNo { get; set; }
        public System.DateTime QuotationMaster_Date { get; set; }
        public string QuotationMaster_Description { get; set; }
        public string QuotationMaster_Type { get; set; }
        public decimal QuotationMaster_TotalAmount { get; set; }
        public decimal QuotationMaster_TotalDiscountAmount { get; set; }
        public decimal QuotationMaster_TaxAmount { get; set; }
        public decimal QuotationMaster_Freight { get; set; }
        public decimal QuotationMaster_SubTotalAmount { get; set; }
        public decimal QuotationMaster_PaidAmount { get; set; }
        public decimal QuotationMaster_DueAmount { get; set; }
        public decimal QuotationMaster_TotalDue { get; set; }
        public System.Guid QuotationMaster_GUID { get; set; }
        public Nullable<int> Customer_SlNo { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Type { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public string CountryName { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_OfficePhone { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Web { get; set; }
        public Nullable<decimal> Purchase_Rate { get; set; }
        public double QuotationDetails_TotalQuantity { get; set; }
        public int Company_SlNo { get; set; }
        public string Company_Name { get; set; }
        public string Repot_Heading { get; set; }
        public byte[] Company_Logo { get; set; }
    }
}
