//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    
    public partial class Get_Cash_TransactionByCode
    {
        public string Tr_Id { get; set; }
        public System.DateTime Tr_date { get; set; }
        public string Tr_Type { get; set; }
        public decimal In_Amount { get; set; }
        public decimal Out_Amount { get; set; }
        public string Tr_Description { get; set; }
        public int Acc_SlNo { get; set; }
        public string Acc_Code { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Description { get; set; }
        public string Acc_Type { get; set; }
    }
}
