//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    
    public partial class Get_Financial_Statement_All
    {
        public string Narration { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public string Description { get; set; }
        public decimal InAmount { get; set; }
        public decimal OutAmount { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<int> Account_SlNo { get; set; }
        public string Account_Code { get; set; }
        public string Account_Name { get; set; }
        public string Account_Address { get; set; }
        public string Account_Mobile { get; set; }
        public string Account_OfficePhone { get; set; }
        public string Account_Phone { get; set; }
        public string Account_Web { get; set; }
        public string Account_Email { get; set; }
        public string Account_Type { get; set; }
    }
}
