//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_QuotationDetails
    {
        public int QuotationDetails_SlNo { get; set; }
        public int QuotationMaster_SlNo { get; set; }
        public int Product_SlNo { get; set; }
        public double QuotationDetails_TotalQuantity { get; set; }
        public Nullable<decimal> Purchase_Rate { get; set; }
        public decimal QuotationDetails_Rate { get; set; }
        public decimal QuotationDetails_Discount { get; set; }
        public decimal QuotationDetails_Tax { get; set; }
        public decimal QuotationDetails_Freight { get; set; }
        public decimal QuotationDetails_TotalAmount { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public int ProductCategory_SlNo { get; set; }
        public string ProductCategory_Name { get; set; }
        public int Unit_SlNo { get; set; }
        public string Unit_Name { get; set; }
    }
}
