//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_CustomerPayment
    {
        public int Tr_SlNo { get; set; }
        public string Tr_Id { get; set; }
        public System.DateTime Tr_date { get; set; }
        public string Tr_Type { get; set; }
        public int Customer_SlNo { get; set; }
        public string Tr_Description { get; set; }
        public decimal In_Amount { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Type { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public string CountryName { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_OfficePhone { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Web { get; set; }
        public decimal Out_Amount { get; set; }
    }
}
