//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_DamageDetails
    {
        public int DamageDetails_SlNo { get; set; }
        public int Product_SlNo { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string Product_BarCode { get; set; }
        public bool Product_IsRawMaterial { get; set; }
        public bool Product_IsFinishedGoods { get; set; }
        public int ProductCategory_SlNo { get; set; }
        public string ProductCategory_Name { get; set; }
        public string ProductCategory_Description { get; set; }
        public string Unit_Name { get; set; }
        public int Damage_SlNo { get; set; }
        public string Damage_InvoiceNo { get; set; }
        public System.DateTime Damage_Date { get; set; }
        public string Damage_Description { get; set; }
        public double DamageDetails_DamageQuantity { get; set; }
    }
}
