//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_PurchaseMaster
    {
        public int PurchaseMaster_SlNo { get; set; }
        public int Supplier_SlNo { get; set; }
        public string Supplier_Code { get; set; }
        public string Supplier_Name { get; set; }
        public int Employee_SlNo { get; set; }
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string PurchaseMaster_InvoiceNo { get; set; }
        public System.DateTime PurchaseMaster_OrderDate { get; set; }
        public string PurchaseMaster_Description { get; set; }
        public string PurchaseMaster_PurchaseType { get; set; }
        public decimal PurchaseMaster_TotalAmount { get; set; }
        public decimal PurchaseMaster_DiscountAmount { get; set; }
        public decimal PurchaseMaster_Tax { get; set; }
        public decimal PurchaseMaster_Freight { get; set; }
        public decimal PurchaseMaster_SubTotalAmount { get; set; }
        public decimal PurchaseMaster_PaidAmount { get; set; }
        public decimal PurchaseMaster_DueAmount { get; set; }
        public System.DateTime PurchaseMaster_ReceiveDate { get; set; }
        public string PurchaseMaster_Status { get; set; }
        public string Supplier_Address { get; set; }
        public string Supplier_Mobile { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_Phone { get; set; }
        public string Supplier_Type { get; set; }
        public string District_Name { get; set; }
        public string CountryName { get; set; }
        public string Supplier_Web { get; set; }
    }
}
