//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_PurchaseReturnMasterDetails
    {
        public int PurchaseReturn_SlNo { get; set; }
        public string PurchaseMaster_InvoiceNo { get; set; }
        public System.DateTime PurchaseReturn_ReturnDate { get; set; }
        public decimal PurchaseReturn_ReturnAmount { get; set; }
        public string PurchaseReturn_Description { get; set; }
        public int PurchaseReturnDetails_SlNo { get; set; }
        public System.DateTime PurchaseReturnDetails_ReturnDate { get; set; }
        public int Product_SlNo { get; set; }
        public double PurchaseReturn_ReturnQuantity { get; set; }
        public decimal PurchaseReturnDetails_ReturnAmount { get; set; }
        public double PurchaseReturnDetails_ReturnQuantity { get; set; }
        public double PurchaseReturnDetails_ReceiveQuantity { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string Product_BarCode { get; set; }
        public string Unit_Name { get; set; }
    }
}
