//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_SupplierTotalPurchaseList
    {
        public decimal Expr1 { get; set; }
        public decimal Expr2 { get; set; }
        public decimal Expr3 { get; set; }
        public decimal Expr4 { get; set; }
        public decimal Expr5 { get; set; }
        public decimal Expr6 { get; set; }
        public Nullable<decimal> PurchaseMaster_DueAmount { get; set; }
        public int Supplier_SlNo { get; set; }
        public string District_Name { get; set; }
        public string CountryName { get; set; }
        public string Supplier_Web { get; set; }
        public string Supplier_Code { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Type { get; set; }
        public string Supplier_Phone { get; set; }
        public string Supplier_Mobile { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_Address { get; set; }
        public string Supplier_OfficePhone { get; set; }
    }
}
