//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_PurchaseInventory
    {
        public int PurchaseInventory_SlNo { get; set; }
        public int Product_SlNo { get; set; }
        public string ProductCategory_Name { get; set; }
        public string ProductCategory_Description { get; set; }
        public string Unit_Name { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string Product_BarCode { get; set; }
        public decimal Product_Purchase_Rate { get; set; }
        public double PurchaseInventory_DamageQuantity { get; set; }
        public double PurchaseInventory_ReturnQuantity { get; set; }
        public double PurchaseInventory_TotalQuantity { get; set; }
        public double PurchaseInventory_ReceiveQuantity { get; set; }
    }
}
