//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SalesChallan
    {
        public int ChallanId { get; set; }
        public string SaleInvoiceNo { get; set; }
        public string SaleChallanNo { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string UpdaeBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
