//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SalesMaster_1
    {
        public int SaleMaster_SlNo { get; set; }
        public string SaleMaster_InvoiceNo { get; set; }
        public string SaleMaster_CalanNo { get; set; }
        public Nullable<int> Customer_SlNo { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public string Customer_Email { get; set; }
        public Nullable<int> Employee_SlNo { get; set; }
        public System.DateTime SaleMaster_SaleDate { get; set; }
        public string SaleMaster_Description { get; set; }
        public string SaleMaster_SaleType { get; set; }
        public decimal SaleMaster_TotalSaleAmount { get; set; }
        public decimal SaleMaster_TotalDiscountAmount { get; set; }
        public decimal SaleMaster_TaxAmount { get; set; }
        public decimal SaleMaster_Freight { get; set; }
        public decimal SaleMaster_SubTotalAmount { get; set; }
        public decimal SaleMaster_PaidAmount { get; set; }
        public decimal SaleMaster_DueAmount { get; set; }
        public decimal SaleMaster_TotalDue { get; set; }
        public Nullable<decimal> SaleMaster_RecievedAmount { get; set; }
        public Nullable<decimal> SaleMaster_ExchangeAmount { get; set; }
        public System.Guid SaleMaster_GUID { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
