//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QuotationMaster
    {
        public int QuotationMaster_SlNo { get; set; }
        public string QuotationMaster_InvoiceNo { get; set; }
        public string QuotationMaster_CallanNo { get; set; }
        public Nullable<int> Customer_SlNo { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public string Customer_Email { get; set; }
        public Nullable<int> Employee_SlNo { get; set; }
        public System.DateTime QuotationMaster_Date { get; set; }
        public string QuotationMaster_Description { get; set; }
        public string QuotationMaster_Type { get; set; }
        public decimal QuotationMaster_TotalAmount { get; set; }
        public decimal QuotationMaster_TotalDiscountAmount { get; set; }
        public decimal QuotationMaster_TaxAmount { get; set; }
        public decimal QuotationMaster_Freight { get; set; }
        public decimal QuotationMaster_SubTotalAmount { get; set; }
        public decimal QuotationMaster_PaidAmount { get; set; }
        public decimal QuotationMaster_DueAmount { get; set; }
        public decimal QuotationMaster_TotalDue { get; set; }
        public System.Guid QuotationMaster_GUID { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
