//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer
    {
        public int Customer_SlNo { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Type { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Mobile { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_OfficePhone { get; set; }
        public string Customer_Address { get; set; }
        public int Country_SlNo { get; set; }
        public string Customer_Web { get; set; }
        public decimal Customer_Credit_Limit { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> District_SlNo { get; set; }
    }
}
