//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SaleReturn
    {
        public int SaleReturn_SlNo { get; set; }
        public string SaleMaster_InvoiceNo { get; set; }
        public System.DateTime SaleReturn_ReturnDate { get; set; }
        public double SaleReturn_ReturnQuantity { get; set; }
        public decimal SaleReturn_ReturnAmount { get; set; }
        public string SaleReturn_Description { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
