//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public int Employee_SlNo { get; set; }
        public int Designation_SlNo { get; set; }
        public int Department_SlNo { get; set; }
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public System.DateTime Employee_JoinDate { get; set; }
        public string Employee_Gender { get; set; }
        public System.DateTime Employee_BirthDate { get; set; }
        public string Employee_NID { get; set; }
        public string Employee_ContactNo { get; set; }
        public string Employee_Email { get; set; }
        public string Employee_MaritalStatus { get; set; }
        public string Employee_FatherName { get; set; }
        public string Employee_MotherName { get; set; }
        public string Employee_PrasentAddress { get; set; }
        public string Employee_PermanentAddress { get; set; }
        public byte[] Employee_Pic { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
