//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CurrentInventory
    {
        public int CurrentInventory_SlNo { get; set; }
        public int Product_SlNo { get; set; }
        public double CurrentInventory_CurrentQuantity { get; set; }
    }
}
