//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PurchaseMaster
    {
        public int PurchaseMaster_SlNo { get; set; }
        public int Supplier_SlNo { get; set; }
        public int Employee_SlNo { get; set; }
        public string PurchaseMaster_InvoiceNo { get; set; }
        public System.DateTime PurchaseMaster_OrderDate { get; set; }
        public string PurchaseMaster_Description { get; set; }
        public string PurchaseMaster_PurchaseType { get; set; }
        public decimal PurchaseMaster_TotalAmount { get; set; }
        public decimal PurchaseMaster_DiscountAmount { get; set; }
        public decimal PurchaseMaster_Tax { get; set; }
        public decimal PurchaseMaster_Freight { get; set; }
        public decimal PurchaseMaster_SubTotalAmount { get; set; }
        public decimal PurchaseMaster_PaidAmount { get; set; }
        public decimal PurchaseMaster_DueAmount { get; set; }
        public System.DateTime PurchaseMaster_ReceiveDate { get; set; }
        public string PurchaseMaster_Status { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.Guid PurchaseMaster_GUID { get; set; }
    }
}
