//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SaleReturnDetails
    {
        public int SaleReturnDetails_SlNo { get; set; }
        public int SaleReturn_SlNo { get; set; }
        public System.DateTime SaleReturnDetails_ReturnDate { get; set; }
        public int Product_SlNo { get; set; }
        public double SaleReturnDetails_SaleQuantity { get; set; }
        public double SaleReturnDetails_ReturnQuantity { get; set; }
        public decimal SaleReturnDetails_ReturnAmount { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
