//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_System
    {
        public int Licence_SlNo { get; set; }
        public string Licence_Key { get; set; }
        public string Licence_StartDate { get; set; }
        public string Licence_EndDate { get; set; }
        public string Licence_NoticeDate { get; set; }
    }
}
