//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Company
    {
        public int Company_SlNo { get; set; }
        public string Company_Name { get; set; }
        public string Repot_Heading { get; set; }
        public byte[] Company_Logo { get; set; }
        public int Invoice_Type { get; set; }
        public string Currency_Name { get; set; }
        public string Currency_Symbol { get; set; }
        public string SubCurrency_Name { get; set; }
        public bool AutoInvoicePrint { get; set; }
    }
}
