//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CashTransaction
    {
        public int Tr_SlNo { get; set; }
        public string Tr_Id { get; set; }
        public System.DateTime Tr_date { get; set; }
        public string Tr_Type { get; set; }
        public Nullable<int> Supplier_SlNo { get; set; }
        public Nullable<int> Customer_SlNo { get; set; }
        public Nullable<int> Acc_SlNo { get; set; }
        public string Acc_Code { get; set; }
        public string Tr_Description { get; set; }
        public decimal In_Amount { get; set; }
        public decimal Out_Amount { get; set; }
        public string Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
