//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CashRegister
    {
        public int Transaction_ID { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public string Narration { get; set; }
        public decimal InAmount { get; set; }
        public decimal OutAmount { get; set; }
        public string Description { get; set; }
        public string Saved_By { get; set; }
        public Nullable<System.DateTime> Saved_Time { get; set; }
        public string Edited_By { get; set; }
        public Nullable<System.DateTime> Edited_Time { get; set; }
        public string IdentityNo { get; set; }
        public string Status { get; set; }
    }
}
