//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Win.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD5;Initial Catalog=xpp;User ID=sa;Password=sa123")]
        public string xppConnectionString {
            get {
                return ((string)(this["xppConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD\\SQLEXPRESS;Initial Catalog=XpressRetail;User ID=sa;Passwor" +
            "d=sa123")]
        public string XpressRetailConnectionString1 {
            get {
                return ((string)(this["XpressRetailConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD\\SQLEXPRESS;Initial Catalog=XpressRetail;Integrated Securit" +
            "y=True")]
        public string XpressRetailConnectionString2 {
            get {
                return ((string)(this["XpressRetailConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD\\SQLEXPRESS;Initial Catalog=XpressRetail;User ID=sa;Passwor" +
            "d=sa123;MultipleActiveResultSets=True")]
        public string XpressRetailConnectionString3 {
            get {
                return ((string)(this["XpressRetailConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD5;Initial Catalog=XpressRetail;User ID=sa;Password=sa123;Mu" +
            "ltipleActiveResultSets=True")]
        public string XpressRetailConnectionString4 {
            get {
                return ((string)(this["XpressRetailConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD\\SQLEXPRESS;Initial Catalog=XpressRetail;User ID=sa;Passwor" +
            "d=sa123")]
        public string XpressRetailConnectionString {
            get {
                return ((string)(this["XpressRetailConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD5;Initial Catalog=XRetail;Integrated Security=True")]
        public string XRetailConnectionString {
            get {
                return ((string)(this["XRetailConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD5\\SQLEXPRESS;Initial Catalog=XpressRetail;Integrated Securi" +
            "ty=True")]
        public string XpressRetailConnectionString5 {
            get {
                return ((string)(this["XpressRetailConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=denar;Initial Catalog=XpressRetail;Persist Security Info=True;User ID" +
            "=sa;Password=sa123")]
        public string XpressRetailConnectionString6 {
            get {
                return ((string)(this["XpressRetailConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD4\\SQLEXPRESS;Initial Catalog=XpressRetail;Persist Security " +
            "Info=True;User ID=sa;Password=link320")]
        public string XpressRetailConnectionString7 {
            get {
                return ((string)(this["XpressRetailConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECBD;Initial Catalog=XpressRetail;Persist Security Info=True;Use" +
            "r ID=sa;Password=link320;MultipleActiveResultSets=True")]
        public string XpressRetailConnectionString8 {
            get {
                return ((string)(this["XpressRetailConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINKTECHBD4\\SQLEXPRESS;Initial Catalog=XpressRetail;Integrated Securi" +
            "ty=True")]
        public string XpressRetailConnectionString9 {
            get {
                return ((string)(this["XpressRetailConnectionString9"]));
            }
        }
    }
}
