//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    
    public partial class IMS_Entities : DbContext
    {
        public IMS_Entities()
            : base("name=IMS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_Country> Tbl_Country { get; set; }
        public DbSet<Tbl_Department> Tbl_Department { get; set; }
        public DbSet<Tbl_Designation> Tbl_Designation { get; set; }
        public DbSet<Tbl_District> Tbl_District { get; set; }
        public DbSet<Tbl_Employee> Tbl_Employee { get; set; }
        public DbSet<Tbl_ProductCategory> Tbl_ProductCategory { get; set; }
        public DbSet<Tbl_Unit> Tbl_Unit { get; set; }
        public DbSet<Tbl_Account> Tbl_Account { get; set; }
        public DbSet<Tbl_Damage> Tbl_Damage { get; set; }
        public DbSet<Tbl_Supplier> Tbl_Supplier { get; set; }
        public DbSet<Qry_Supplier> Qry_Supplier { get; set; }
        public DbSet<Tbl_User> Tbl_User { get; set; }
        public DbSet<Qry_Employee> Qry_Employee { get; set; }
        public DbSet<Qry_BankStatement> Qry_BankStatement { get; set; }
        public DbSet<Qry_SupplierPayment> Qry_SupplierPayment { get; set; }
        public DbSet<Qry_SupplierTotalPurchaseList> Qry_SupplierTotalPurchaseList { get; set; }
        public DbSet<Tbl_Customer> Tbl_Customer { get; set; }
        public DbSet<Qry_SupplierDue> Qry_SupplierDue { get; set; }
        public DbSet<Tbl_System> Tbl_System { get; set; }
        public DbSet<Qry_SalesMaster> Qry_SalesMaster { get; set; }
        public DbSet<Qry_PurchaseMaster> Qry_PurchaseMaster { get; set; }
        public DbSet<Tbl_CurrentInventory> Tbl_CurrentInventory { get; set; }
        public DbSet<Tbl_PurchaseDetails> Tbl_PurchaseDetails { get; set; }
        public DbSet<Qry_PurchaseDetails> Qry_PurchaseDetails { get; set; }
        public DbSet<Tbl_DamageDetails> Tbl_DamageDetails { get; set; }
        public DbSet<Tbl_PurchaseReturn> Tbl_PurchaseReturn { get; set; }
        public DbSet<Tbl_PurchaseReturnDetails> Tbl_PurchaseReturnDetails { get; set; }
        public DbSet<Tbl_SaleReturn> Tbl_SaleReturn { get; set; }
        public DbSet<Tbl_SaleReturnDetails> Tbl_SaleReturnDetails { get; set; }
        public DbSet<Qry_CurrentInventory> Qry_CurrentInventory { get; set; }
        public DbSet<Qry_DamageDetails> Qry_DamageDetails { get; set; }
        public DbSet<Qry_PurchaseMasterDetails> Qry_PurchaseMasterDetails { get; set; }
        public DbSet<Qry_PurchaseReturnDetails> Qry_PurchaseReturnDetails { get; set; }
        public DbSet<Qry_PurchaseReturnMasterDetails> Qry_PurchaseReturnMasterDetails { get; set; }
        public DbSet<Qry_SaleMasterDetails> Qry_SaleMasterDetails { get; set; }
        public DbSet<Qry_SaleReturnDetails> Qry_SaleReturnDetails { get; set; }
        public DbSet<Qry_SaleReturnMasterDetails> Qry_SaleReturnMasterDetails { get; set; }
        public DbSet<Qry_SalesDetails> Qry_SalesDetails { get; set; }
        public DbSet<Qry_SalesInventory> Qry_SalesInventory { get; set; }
        public DbSet<Qry_SalesPurchaseDetails> Qry_SalesPurchaseDetails { get; set; }
        public DbSet<Tbl_SaleInventory> Tbl_SaleInventory { get; set; }
        public DbSet<Tbl_SaleDetails> Tbl_SaleDetails { get; set; }
        public DbSet<Qry_PurchaseInvoice> Qry_PurchaseInvoice { get; set; }
        public DbSet<Qry_SalesInvoice> Qry_SalesInvoice { get; set; }
        public DbSet<Tbl_PurchaseMaster> Tbl_PurchaseMaster { get; set; }
        public DbSet<Tbl_CashRegister> Tbl_CashRegister { get; set; }
        public DbSet<Tbl_PurchaseInventory> Tbl_PurchaseInventory { get; set; }
        public DbSet<Qry_PurchaseInventory> Qry_PurchaseInventory { get; set; }
        public DbSet<Tbl_CashTransaction> Tbl_CashTransaction { get; set; }
        public DbSet<Qry_CashTransaction> Qry_CashTransaction { get; set; }
        public DbSet<Qry_CustomerPayment> Qry_CustomerPayment { get; set; }
        public DbSet<Tbl_Product> Tbl_Product { get; set; }
        public DbSet<Qry_Product> Qry_Product { get; set; }
        public DbSet<Tbl_SalesChallan> Tbl_SalesChallan { get; set; }
        public DbSet<Tbl_QuotationDetails> Tbl_QuotationDetails { get; set; }
        public DbSet<Tbl_QuotationMaster> Tbl_QuotationMaster { get; set; }
        public DbSet<Qry_QuotationDetails> Qry_QuotationDetails { get; set; }
        public DbSet<Tbl_SalesMaster> Tbl_SalesMaster { get; set; }
        public DbSet<Tbl_Company> Tbl_Company { get; set; }
        public DbSet<Qry_Customer> Qry_Customer { get; set; }
        public DbSet<Qry_CustomerDue> Qry_CustomerDue { get; set; }
        public DbSet<Tbl_SaleDetails_1> Tbl_SaleDetails_1 { get; set; }
        public DbSet<Tbl_SalesMaster_1> Tbl_SalesMaster_1 { get; set; }
    
        public virtual ObjectResult<func_GetReorderProduct> func_GetReorderProduct()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(func_GetReorderProduct).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<func_GetReorderProduct>("func_GetReorderProduct");
        }
    
        public virtual ObjectResult<Func_Get_BankStatement> Func_Get_BankStatement()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Func_Get_BankStatement).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Func_Get_BankStatement>("Func_Get_BankStatement");
        }
    
        public virtual ObjectResult<Get_Expense_Statement> Get_Expense_Statement()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_Expense_Statement).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Expense_Statement>("Get_Expense_Statement");
        }
    
        public virtual ObjectResult<Get_Financial_Statement> Get_Financial_Statement()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_Financial_Statement).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Financial_Statement>("Get_Financial_Statement");
        }
    
        public virtual ObjectResult<Get_DamagedProduct> Get_DamagedProduct()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_DamagedProduct).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DamagedProduct>("Get_DamagedProduct");
        }
    
        public virtual ObjectResult<Func_TotalStockwithValue> Func_TotalStockwithValue()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Func_TotalStockwithValue).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Func_TotalStockwithValue>("Func_TotalStockwithValue");
        }
    
        public virtual ObjectResult<Func_TotalStock> Func_TotalStock()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Func_TotalStock).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Func_TotalStock>("Func_TotalStock");
        }
    
        public virtual ObjectResult<Get_Cash_TransactionByCode> Get_Cash_TransactionByCode()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_Cash_TransactionByCode).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Cash_TransactionByCode>("Get_Cash_TransactionByCode");
        }
    
        public virtual ObjectResult<GetItemCurrentStock> GetItemCurrentStock()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(GetItemCurrentStock).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemCurrentStock>("GetItemCurrentStock");
        }
    
        public virtual ObjectResult<Get_SaleInvoiceByChallan> Get_SaleInvoiceByChallan()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_SaleInvoiceByChallan).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SaleInvoiceByChallan>("Get_SaleInvoiceByChallan");
        }
    
        public virtual ObjectResult<Get_Financial_Statement_CustomerWise> Get_Financial_Statement_CustomerWise(Nullable<int> customerSlNo)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_Financial_Statement_CustomerWise).Assembly);
    
            var customerSlNoParameter = customerSlNo.HasValue ?
                new ObjectParameter("CustomerSlNo", customerSlNo) :
                new ObjectParameter("CustomerSlNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Financial_Statement_CustomerWise>("Get_Financial_Statement_CustomerWise", customerSlNoParameter);
        }
    
        public virtual ObjectResult<Get_Financial_Statement_All> Get_Financial_Statement_All()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_Financial_Statement_All).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Financial_Statement_All>("Get_Financial_Statement_All");
        }
    
        public virtual ObjectResult<GetSaleMasterDetails> GetSaleMasterDetails()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(GetSaleMasterDetails).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSaleMasterDetails>("GetSaleMasterDetails");
        }
    
        public virtual ObjectResult<Get_SaleInvoice> Get_SaleInvoice()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_SaleInvoice).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SaleInvoice>("Get_SaleInvoice");
        }
    
        public virtual ObjectResult<Get_SaleMaster> Get_SaleMaster()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_SaleMaster).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SaleMaster>("Get_SaleMaster");
        }
    
        public virtual ObjectResult<Get_SaleInvoiceByQuotation> Get_SaleInvoiceByQuotation()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_SaleInvoiceByQuotation).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SaleInvoiceByQuotation>("Get_SaleInvoiceByQuotation");
        }
    
        public virtual ObjectResult<Get_SaleInvoice_1> Get_SaleInvoice_1()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Get_SaleInvoice_1).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SaleInvoice_1>("Get_SaleInvoice_1");
        }
    }
}
